[package]
name = "bump-stack"
version = "0.1.0"
edition = "2024"
license = "MPL-2.0"
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/quendimax/bump-stack"
authors = ["Maksim Tomkavich <quendimax@gmail.com>"]

description = "A stack implementation using bump allocation"
keywords = ["lifo", "stack", "bump", "no_std"]
categories = ["data-structures", "no-std"]

[dependencies]

[dev-dependencies]
pretty_assertions = "1"
